
// Code generated by stanc v2.27.0
#include <stan/model/model_header.hpp>
namespace vasishth_model_namespace {

using stan::io::dump;
using stan::model::assign;
using stan::model::index_uni;
using stan::model::index_max;
using stan::model::index_min;
using stan::model::index_min_max;
using stan::model::index_multi;
using stan::model::index_omni;
using stan::model::model_base_crtp;
using stan::model::rvalue;
using namespace stan::math;


stan::math::profile_map profiles__;
static constexpr std::array<const char*, 38> locations_array__ = 
{" (found before start of program)",
 " (in '/Users/claytonroberts/Documents/TROPOMI_LHM/src/models/vasishth.stan', line 11, column 2 to column 32)",
 " (in '/Users/claytonroberts/Documents/TROPOMI_LHM/src/models/vasishth.stan', line 12, column 2 to column 32)",
 " (in '/Users/claytonroberts/Documents/TROPOMI_LHM/src/models/vasishth.stan', line 13, column 2 to column 35)",
 " (in '/Users/claytonroberts/Documents/TROPOMI_LHM/src/models/vasishth.stan', line 14, column 2 to column 34)",
 " (in '/Users/claytonroberts/Documents/TROPOMI_LHM/src/models/vasishth.stan', line 15, column 2 to column 30)",
 " (in '/Users/claytonroberts/Documents/TROPOMI_LHM/src/models/vasishth.stan', line 16, column 2 to column 30)",
 " (in '/Users/claytonroberts/Documents/TROPOMI_LHM/src/models/vasishth.stan', line 19, column 2 to column 17)",
 " (in '/Users/claytonroberts/Documents/TROPOMI_LHM/src/models/vasishth.stan', line 20, column 2 to column 45)",
 " (in '/Users/claytonroberts/Documents/TROPOMI_LHM/src/models/vasishth.stan', line 44, column 2 to column 42)",
 " (in '/Users/claytonroberts/Documents/TROPOMI_LHM/src/models/vasishth.stan', line 45, column 2 to column 37)",
 " (in '/Users/claytonroberts/Documents/TROPOMI_LHM/src/models/vasishth.stan', line 46, column 2 to column 37)",
 " (in '/Users/claytonroberts/Documents/TROPOMI_LHM/src/models/vasishth.stan', line 47, column 2 to column 40)",
 " (in '/Users/claytonroberts/Documents/TROPOMI_LHM/src/models/vasishth.stan', line 48, column 2 to column 40)",
 " (in '/Users/claytonroberts/Documents/TROPOMI_LHM/src/models/vasishth.stan', line 24, column 4 to column 45)",
 " (in '/Users/claytonroberts/Documents/TROPOMI_LHM/src/models/vasishth.stan', line 25, column 4 to column 45)",
 " (in '/Users/claytonroberts/Documents/TROPOMI_LHM/src/models/vasishth.stan', line 29, column 4 to line 30, column 32)",
 " (in '/Users/claytonroberts/Documents/TROPOMI_LHM/src/models/vasishth.stan', line 31, column 4 to line 32, column 33)",
 " (in '/Users/claytonroberts/Documents/TROPOMI_LHM/src/models/vasishth.stan', line 33, column 4 to column 46)",
 " (in '/Users/claytonroberts/Documents/TROPOMI_LHM/src/models/vasishth.stan', line 34, column 4 to column 46)",
 " (in '/Users/claytonroberts/Documents/TROPOMI_LHM/src/models/vasishth.stan', line 37, column 4 to line 41, column 70)",
 " (in '/Users/claytonroberts/Documents/TROPOMI_LHM/src/models/vasishth.stan', line 2, column 2 to column 26)",
 " (in '/Users/claytonroberts/Documents/TROPOMI_LHM/src/models/vasishth.stan', line 3, column 9 to column 10)",
 " (in '/Users/claytonroberts/Documents/TROPOMI_LHM/src/models/vasishth.stan', line 3, column 2 to column 32)",
 " (in '/Users/claytonroberts/Documents/TROPOMI_LHM/src/models/vasishth.stan', line 4, column 9 to column 10)",
 " (in '/Users/claytonroberts/Documents/TROPOMI_LHM/src/models/vasishth.stan', line 4, column 2 to column 32)",
 " (in '/Users/claytonroberts/Documents/TROPOMI_LHM/src/models/vasishth.stan', line 5, column 18 to column 19)",
 " (in '/Users/claytonroberts/Documents/TROPOMI_LHM/src/models/vasishth.stan', line 5, column 2 to column 32)",
 " (in '/Users/claytonroberts/Documents/TROPOMI_LHM/src/models/vasishth.stan', line 6, column 18 to column 19)",
 " (in '/Users/claytonroberts/Documents/TROPOMI_LHM/src/models/vasishth.stan', line 6, column 2 to column 32)",
 " (in '/Users/claytonroberts/Documents/TROPOMI_LHM/src/models/vasishth.stan', line 7, column 2 to column 26)",
 " (in '/Users/claytonroberts/Documents/TROPOMI_LHM/src/models/vasishth.stan', line 8, column 31 to column 32)",
 " (in '/Users/claytonroberts/Documents/TROPOMI_LHM/src/models/vasishth.stan', line 8, column 2 to column 34)",
 " (in '/Users/claytonroberts/Documents/TROPOMI_LHM/src/models/vasishth.stan', line 11, column 18 to column 19)",
 " (in '/Users/claytonroberts/Documents/TROPOMI_LHM/src/models/vasishth.stan', line 15, column 12 to column 13)",
 " (in '/Users/claytonroberts/Documents/TROPOMI_LHM/src/models/vasishth.stan', line 19, column 9 to column 10)",
 " (in '/Users/claytonroberts/Documents/TROPOMI_LHM/src/models/vasishth.stan', line 45, column 9 to column 10)",
 " (in '/Users/claytonroberts/Documents/TROPOMI_LHM/src/models/vasishth.stan', line 46, column 9 to column 10)"};



class vasishth_model final : public model_base_crtp<vasishth_model> {

 private:
  int M;
  Eigen::Matrix<double, -1, 1> CH4_obs__;
  Eigen::Matrix<double, -1, 1> NO2_obs__;
  Eigen::Matrix<double, -1, 1> sigma_N__;
  Eigen::Matrix<double, -1, 1> sigma_C__;
  int D;
  std::vector<int> day_id; 
  Eigen::Map<Eigen::Matrix<double, -1, 1>> CH4_obs{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double, -1, 1>> NO2_obs{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double, -1, 1>> sigma_N{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double, -1, 1>> sigma_C{nullptr, 0};
 
 public:
  ~vasishth_model() { }
  
  inline std::string model_name() const final { return "vasishth_model"; }

  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.27.0", "stancflags = "};
  }
  
  
  vasishth_model(stan::io::var_context& context__,
                 unsigned int random_seed__ = 0,
                 std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double ;
    boost::ecuyer1988 base_rng__ = 
        stan::services::util::create_rng(random_seed__, 0);
    (void) base_rng__;  // suppress unused var warning
    static constexpr const char* function__ = "vasishth_model_namespace::vasishth_model";
    (void) function__;  // suppress unused var warning
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      current_statement__ = 21;
      context__.validate_dims("data initialization","M","int",
           std::vector<size_t>{});
      M = std::numeric_limits<int>::min();
      
      current_statement__ = 21;
      M = context__.vals_i("M")[(1 - 1)];
      current_statement__ = 21;
      check_greater_or_equal(function__, "M", M, 1);
      current_statement__ = 22;
      validate_non_negative_index("CH4_obs", "M", M);
      current_statement__ = 23;
      context__.validate_dims("data initialization","CH4_obs","double",
           std::vector<size_t>{static_cast<size_t>(M)});
      CH4_obs__ = Eigen::Matrix<double, -1, 1>(M);
      new (&CH4_obs) Eigen::Map<Eigen::Matrix<double, -1, 1>>(CH4_obs__.data(), M);
      
      
      {
        std::vector<local_scalar_t__> CH4_obs_flat__;
        current_statement__ = 23;
        CH4_obs_flat__ = context__.vals_r("CH4_obs");
        current_statement__ = 23;
        pos__ = 1;
        current_statement__ = 23;
        for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
          current_statement__ = 23;
          assign(CH4_obs, CH4_obs_flat__[(pos__ - 1)],
            "assigning variable CH4_obs", index_uni(sym1__));
          current_statement__ = 23;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 24;
      validate_non_negative_index("NO2_obs", "M", M);
      current_statement__ = 25;
      context__.validate_dims("data initialization","NO2_obs","double",
           std::vector<size_t>{static_cast<size_t>(M)});
      NO2_obs__ = Eigen::Matrix<double, -1, 1>(M);
      new (&NO2_obs) Eigen::Map<Eigen::Matrix<double, -1, 1>>(NO2_obs__.data(), M);
      
      
      {
        std::vector<local_scalar_t__> NO2_obs_flat__;
        current_statement__ = 25;
        NO2_obs_flat__ = context__.vals_r("NO2_obs");
        current_statement__ = 25;
        pos__ = 1;
        current_statement__ = 25;
        for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
          current_statement__ = 25;
          assign(NO2_obs, NO2_obs_flat__[(pos__ - 1)],
            "assigning variable NO2_obs", index_uni(sym1__));
          current_statement__ = 25;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 26;
      validate_non_negative_index("sigma_N", "M", M);
      current_statement__ = 27;
      context__.validate_dims("data initialization","sigma_N","double",
           std::vector<size_t>{static_cast<size_t>(M)});
      sigma_N__ = Eigen::Matrix<double, -1, 1>(M);
      new (&sigma_N) Eigen::Map<Eigen::Matrix<double, -1, 1>>(sigma_N__.data(), M);
      
      
      {
        std::vector<local_scalar_t__> sigma_N_flat__;
        current_statement__ = 27;
        sigma_N_flat__ = context__.vals_r("sigma_N");
        current_statement__ = 27;
        pos__ = 1;
        current_statement__ = 27;
        for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
          current_statement__ = 27;
          assign(sigma_N, sigma_N_flat__[(pos__ - 1)],
            "assigning variable sigma_N", index_uni(sym1__));
          current_statement__ = 27;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 27;
      for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
        current_statement__ = 27;
        check_greater_or_equal(function__, "sigma_N[sym1__]",
                               sigma_N[(sym1__ - 1)], 0);
      }
      current_statement__ = 28;
      validate_non_negative_index("sigma_C", "M", M);
      current_statement__ = 29;
      context__.validate_dims("data initialization","sigma_C","double",
           std::vector<size_t>{static_cast<size_t>(M)});
      sigma_C__ = Eigen::Matrix<double, -1, 1>(M);
      new (&sigma_C) Eigen::Map<Eigen::Matrix<double, -1, 1>>(sigma_C__.data(), M);
      
      
      {
        std::vector<local_scalar_t__> sigma_C_flat__;
        current_statement__ = 29;
        sigma_C_flat__ = context__.vals_r("sigma_C");
        current_statement__ = 29;
        pos__ = 1;
        current_statement__ = 29;
        for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
          current_statement__ = 29;
          assign(sigma_C, sigma_C_flat__[(pos__ - 1)],
            "assigning variable sigma_C", index_uni(sym1__));
          current_statement__ = 29;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 29;
      for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
        current_statement__ = 29;
        check_greater_or_equal(function__, "sigma_C[sym1__]",
                               sigma_C[(sym1__ - 1)], 0);
      }
      current_statement__ = 30;
      context__.validate_dims("data initialization","D","int",
           std::vector<size_t>{});
      D = std::numeric_limits<int>::min();
      
      current_statement__ = 30;
      D = context__.vals_i("D")[(1 - 1)];
      current_statement__ = 30;
      check_greater_or_equal(function__, "D", D, 1);
      current_statement__ = 31;
      validate_non_negative_index("day_id", "M", M);
      current_statement__ = 32;
      context__.validate_dims("data initialization","day_id","int",
           std::vector<size_t>{static_cast<size_t>(M)});
      day_id = std::vector<int>(M, std::numeric_limits<int>::min());
      
      current_statement__ = 32;
      day_id = context__.vals_i("day_id");
      current_statement__ = 32;
      for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
        current_statement__ = 32;
        check_greater_or_equal(function__, "day_id[sym1__]",
                               day_id[(sym1__ - 1)], 1);
      }
      current_statement__ = 32;
      for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
        current_statement__ = 32;
        check_less_or_equal(function__, "day_id[sym1__]",
                            day_id[(sym1__ - 1)], D);
      }
      current_statement__ = 33;
      validate_non_negative_index("gamma", "D", D);
      current_statement__ = 34;
      validate_non_negative_index("z_u", "D", D);
      current_statement__ = 35;
      validate_non_negative_index("u", "D", D);
      current_statement__ = 36;
      validate_non_negative_index("alpha", "D", D);
      current_statement__ = 37;
      validate_non_negative_index("beta", "D", D);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    num_params_r__ = D + 2 + 1 + 1 + (2 * D) + ((2 * (2 - 1)) / 2);
    
  }
  
  template <bool propto__, bool jacobian__ , typename VecR, typename VecI, 
  stan::require_vector_like_t<VecR>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr> 
  inline stan::scalar_type_t<VecR> log_prob_impl(VecR& params_r__,
                                                 VecI& params_i__,
                                                 std::ostream* pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    static constexpr const char* function__ = "vasishth_model_namespace::log_prob";
    (void) function__;  // suppress unused var warning
    
    try {
      Eigen::Matrix<local_scalar_t__, -1, 1> gamma;
      gamma = Eigen::Matrix<local_scalar_t__, -1, 1>(D);
      stan::math::fill(gamma, DUMMY_VAR__);
      
      current_statement__ = 1;
      gamma = in__.template read_constrain_lb<Eigen::Matrix<local_scalar_t__, -1, 1>, jacobian__>(
                0, lp__, D);
      Eigen::Matrix<local_scalar_t__, -1, 1> tau_u;
      tau_u = Eigen::Matrix<local_scalar_t__, -1, 1>(2);
      stan::math::fill(tau_u, DUMMY_VAR__);
      
      current_statement__ = 2;
      tau_u = in__.template read_constrain_lb<Eigen::Matrix<local_scalar_t__, -1, 1>, jacobian__>(
                0, lp__, 2);
      local_scalar_t__ mu_alpha;
      mu_alpha = DUMMY_VAR__;
      
      current_statement__ = 3;
      mu_alpha = in__.template read<local_scalar_t__>();
      local_scalar_t__ mu_beta;
      mu_beta = DUMMY_VAR__;
      
      current_statement__ = 4;
      mu_beta = in__.template read<local_scalar_t__>();
      Eigen::Matrix<local_scalar_t__, -1, -1> z_u;
      z_u = Eigen::Matrix<local_scalar_t__, -1, -1>(2, D);
      stan::math::fill(z_u, DUMMY_VAR__);
      
      current_statement__ = 5;
      z_u = in__.template read<Eigen::Matrix<local_scalar_t__, -1, -1>>(2, D);
      Eigen::Matrix<local_scalar_t__, -1, -1> L_u;
      L_u = Eigen::Matrix<local_scalar_t__, -1, -1>(2, 2);
      stan::math::fill(L_u, DUMMY_VAR__);
      
      current_statement__ = 6;
      L_u = in__.template read_constrain_cholesky_factor_corr<Eigen::Matrix<local_scalar_t__, -1, -1>, jacobian__>(
              lp__, 2);
      Eigen::Matrix<local_scalar_t__, -1, -1> u;
      u = Eigen::Matrix<local_scalar_t__, -1, -1>(D, 2);
      stan::math::fill(u, DUMMY_VAR__);
      
      current_statement__ = 8;
      assign(u, transpose(multiply(diag_pre_multiply(tau_u, L_u), z_u)),
        "assigning variable u");
      {
        current_statement__ = 14;
        lp_accum__.add(normal_lpdf<false>(mu_alpha, 1865, 10));
        current_statement__ = 15;
        lp_accum__.add(normal_lpdf<false>(mu_beta, 1.0, 0.3));
        current_statement__ = 16;
        lp_accum__.add(
          (normal_lpdf<false>(rvalue(tau_u, "tau_u", index_uni(1)), 0, 20) -
            normal_lccdf(0, 0, 20)));
        current_statement__ = 17;
        lp_accum__.add(
          (normal_lpdf<false>(rvalue(tau_u, "tau_u", index_uni(2)), 0, 0.5) -
            normal_lccdf(0, 0, 0.5)));
        current_statement__ = 18;
        lp_accum__.add(lkj_corr_cholesky_lpdf<false>(L_u, 2));
        current_statement__ = 19;
        lp_accum__.add(std_normal_lpdf<false>(to_vector(z_u)));
        current_statement__ = 20;
        lp_accum__.add(
          normal_lpdf<false>(CH4_obs,
            add(
              add(mu_alpha,
                rvalue(u, "u", index_multi(day_id), index_uni(1))),
              elt_multiply(NO2_obs,
                add(mu_beta,
                  rvalue(u, "u", index_multi(day_id), index_uni(2))))),
            stan::math::sqrt(
              add(
                add(square(rvalue(gamma, "gamma", index_multi(day_id))),
                  square(sigma_C)),
                square(
                  elt_multiply(sigma_N,
                    add(mu_beta,
                      rvalue(u, "u", index_multi(day_id), index_uni(2)))))))));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
    } // log_prob_impl() 
    
  template <typename RNG, typename VecR, typename VecI, typename VecVar, 
  stan::require_vector_like_vt<std::is_floating_point, VecR>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr, 
  stan::require_std_vector_vt<std::is_floating_point, VecVar>* = nullptr> 
  inline void write_array_impl(RNG& base_rng__, VecR& params_r__,
                               VecI& params_i__, VecVar& vars__,
                               const bool emit_transformed_parameters__ = true,
                               const bool emit_generated_quantities__ = true,
                               std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    vars__.resize(0);
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    static constexpr bool propto__ = true;
    (void) propto__;
    double lp__ = 0.0;
    (void) lp__;  // dummy to suppress unused var warning
    int current_statement__ = 0; 
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    constexpr bool jacobian__ = false;
    (void) DUMMY_VAR__;  // suppress unused var warning
    static constexpr const char* function__ = "vasishth_model_namespace::write_array";
    (void) function__;  // suppress unused var warning
    
    try {
      Eigen::Matrix<double, -1, 1> gamma;
      gamma = Eigen::Matrix<double, -1, 1>(D);
      stan::math::fill(gamma, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 1;
      gamma = in__.template read_constrain_lb<Eigen::Matrix<local_scalar_t__, -1, 1>, jacobian__>(
                0, lp__, D);
      Eigen::Matrix<double, -1, 1> tau_u;
      tau_u = Eigen::Matrix<double, -1, 1>(2);
      stan::math::fill(tau_u, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 2;
      tau_u = in__.template read_constrain_lb<Eigen::Matrix<local_scalar_t__, -1, 1>, jacobian__>(
                0, lp__, 2);
      double mu_alpha;
      mu_alpha = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 3;
      mu_alpha = in__.template read<local_scalar_t__>();
      double mu_beta;
      mu_beta = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 4;
      mu_beta = in__.template read<local_scalar_t__>();
      Eigen::Matrix<double, -1, -1> z_u;
      z_u = Eigen::Matrix<double, -1, -1>(2, D);
      stan::math::fill(z_u, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 5;
      z_u = in__.template read<Eigen::Matrix<local_scalar_t__, -1, -1>>(2, D);
      Eigen::Matrix<double, -1, -1> L_u;
      L_u = Eigen::Matrix<double, -1, -1>(2, 2);
      stan::math::fill(L_u, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 6;
      L_u = in__.template read_constrain_cholesky_factor_corr<Eigen::Matrix<local_scalar_t__, -1, -1>, jacobian__>(
              lp__, 2);
      Eigen::Matrix<double, -1, -1> u;
      u = Eigen::Matrix<double, -1, -1>(D, 2);
      stan::math::fill(u, std::numeric_limits<double>::quiet_NaN());
      
      for (int sym1__ = 1; sym1__ <= D; ++sym1__) {
        vars__.emplace_back(gamma[(sym1__ - 1)]);
      }
      for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
        vars__.emplace_back(tau_u[(sym1__ - 1)]);
      }
      vars__.emplace_back(mu_alpha);
      vars__.emplace_back(mu_beta);
      for (int sym1__ = 1; sym1__ <= D; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= 2; ++sym2__) {
          vars__.emplace_back(
            rvalue(z_u, "z_u", index_uni(sym2__), index_uni(sym1__)));
        }
      }
      for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= 2; ++sym2__) {
          vars__.emplace_back(
            rvalue(L_u, "L_u", index_uni(sym2__), index_uni(sym1__)));
        }
      }
      if (logical_negation((primitive_value(emit_transformed_parameters__) ||
            primitive_value(emit_generated_quantities__)))) {
        return ;
      } 
      current_statement__ = 8;
      assign(u, transpose(multiply(diag_pre_multiply(tau_u, L_u), z_u)),
        "assigning variable u");
      if (emit_transformed_parameters__) {
        for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
          for (int sym2__ = 1; sym2__ <= D; ++sym2__) {
            vars__.emplace_back(
              rvalue(u, "u", index_uni(sym2__), index_uni(sym1__)));
          }
        }
      } 
      if (logical_negation(emit_generated_quantities__)) {
        return ;
      } 
      Eigen::Matrix<double, -1, -1> rho_u;
      rho_u = Eigen::Matrix<double, -1, -1>(2, 2);
      stan::math::fill(rho_u, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 9;
      assign(rho_u, multiply(L_u, transpose(L_u)), "assigning variable rho_u");
      Eigen::Matrix<double, -1, 1> alpha;
      alpha = Eigen::Matrix<double, -1, 1>(D);
      stan::math::fill(alpha, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 10;
      assign(alpha, rvalue(u, "u", index_omni(), index_uni(1)),
        "assigning variable alpha");
      Eigen::Matrix<double, -1, 1> beta;
      beta = Eigen::Matrix<double, -1, 1>(D);
      stan::math::fill(beta, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 11;
      assign(beta, rvalue(u, "u", index_omni(), index_uni(2)),
        "assigning variable beta");
      double sigma_alpha;
      sigma_alpha = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 12;
      sigma_alpha = rvalue(tau_u, "tau_u", index_uni(1));
      double sigma_beta;
      sigma_beta = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 13;
      sigma_beta = rvalue(tau_u, "tau_u", index_uni(2));
      current_statement__ = 9;
      check_corr_matrix(function__, "rho_u", rho_u);
      for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= 2; ++sym2__) {
          vars__.emplace_back(
            rvalue(rho_u, "rho_u", index_uni(sym2__), index_uni(sym1__)));
        }
      }
      for (int sym1__ = 1; sym1__ <= D; ++sym1__) {
        vars__.emplace_back(alpha[(sym1__ - 1)]);
      }
      for (int sym1__ = 1; sym1__ <= D; ++sym1__) {
        vars__.emplace_back(beta[(sym1__ - 1)]);
      }
      vars__.emplace_back(sigma_alpha);
      vars__.emplace_back(sigma_beta);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // write_array_impl() 
    
  template <typename VecVar, typename VecI, 
  stan::require_std_vector_t<VecVar>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr> 
  inline void transform_inits_impl(const stan::io::var_context& context__,
                                   VecI& params_i__, VecVar& vars__,
                                   std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    vars__.clear();
    vars__.reserve(num_params_r__);
    int current_statement__ = 0; 
    
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      Eigen::Matrix<double, -1, 1> gamma;
      gamma = Eigen::Matrix<double, -1, 1>(D);
      stan::math::fill(gamma, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> gamma_flat__;
        current_statement__ = 1;
        gamma_flat__ = context__.vals_r("gamma");
        current_statement__ = 1;
        pos__ = 1;
        current_statement__ = 1;
        for (int sym1__ = 1; sym1__ <= D; ++sym1__) {
          current_statement__ = 1;
          assign(gamma, gamma_flat__[(pos__ - 1)],
            "assigning variable gamma", index_uni(sym1__));
          current_statement__ = 1;
          pos__ = (pos__ + 1);
        }
      }
      Eigen::Matrix<double, -1, 1> gamma_free__;
      gamma_free__ = Eigen::Matrix<double, -1, 1>(D);
      stan::math::fill(gamma_free__, std::numeric_limits<double>::quiet_NaN());
      
      
      current_statement__ = 1;
      for (int sym1__ = 1; sym1__ <= D; ++sym1__) {
        current_statement__ = 1;
        assign(gamma_free__, stan::math::lb_free(gamma[(sym1__ - 1)], 0),
          "assigning variable gamma_free__", index_uni(sym1__));
      }
      Eigen::Matrix<double, -1, 1> tau_u;
      tau_u = Eigen::Matrix<double, -1, 1>(2);
      stan::math::fill(tau_u, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> tau_u_flat__;
        current_statement__ = 2;
        tau_u_flat__ = context__.vals_r("tau_u");
        current_statement__ = 2;
        pos__ = 1;
        current_statement__ = 2;
        for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
          current_statement__ = 2;
          assign(tau_u, tau_u_flat__[(pos__ - 1)],
            "assigning variable tau_u", index_uni(sym1__));
          current_statement__ = 2;
          pos__ = (pos__ + 1);
        }
      }
      Eigen::Matrix<double, -1, 1> tau_u_free__;
      tau_u_free__ = Eigen::Matrix<double, -1, 1>(2);
      stan::math::fill(tau_u_free__, std::numeric_limits<double>::quiet_NaN());
      
      
      current_statement__ = 2;
      for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
        current_statement__ = 2;
        assign(tau_u_free__, stan::math::lb_free(tau_u[(sym1__ - 1)], 0),
          "assigning variable tau_u_free__", index_uni(sym1__));
      }
      double mu_alpha;
      mu_alpha = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 3;
      mu_alpha = context__.vals_r("mu_alpha")[(1 - 1)];
      double mu_beta;
      mu_beta = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 4;
      mu_beta = context__.vals_r("mu_beta")[(1 - 1)];
      Eigen::Matrix<double, -1, -1> z_u;
      z_u = Eigen::Matrix<double, -1, -1>(2, D);
      stan::math::fill(z_u, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> z_u_flat__;
        current_statement__ = 5;
        z_u_flat__ = context__.vals_r("z_u");
        current_statement__ = 5;
        pos__ = 1;
        current_statement__ = 5;
        for (int sym1__ = 1; sym1__ <= D; ++sym1__) {
          current_statement__ = 5;
          for (int sym2__ = 1; sym2__ <= 2; ++sym2__) {
            current_statement__ = 5;
            assign(z_u, z_u_flat__[(pos__ - 1)],
              "assigning variable z_u", index_uni(sym2__), index_uni(sym1__));
            current_statement__ = 5;
            pos__ = (pos__ + 1);
          }
        }
      }
      Eigen::Matrix<double, -1, -1> L_u;
      L_u = Eigen::Matrix<double, -1, -1>(2, 2);
      stan::math::fill(L_u, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> L_u_flat__;
        current_statement__ = 6;
        L_u_flat__ = context__.vals_r("L_u");
        current_statement__ = 6;
        pos__ = 1;
        current_statement__ = 6;
        for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
          current_statement__ = 6;
          for (int sym2__ = 1; sym2__ <= 2; ++sym2__) {
            current_statement__ = 6;
            assign(L_u, L_u_flat__[(pos__ - 1)],
              "assigning variable L_u", index_uni(sym2__), index_uni(sym1__));
            current_statement__ = 6;
            pos__ = (pos__ + 1);
          }
        }
      }
      Eigen::Matrix<double, -1, 1> L_u_free__;
      L_u_free__ = Eigen::Matrix<double, -1, 1>(((2 * (2 - 1)) / 2));
      stan::math::fill(L_u_free__, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 6;
      assign(L_u_free__, stan::math::cholesky_corr_free(L_u),
        "assigning variable L_u_free__");
      for (int sym1__ = 1; sym1__ <= D; ++sym1__) {
        vars__.emplace_back(gamma_free__[(sym1__ - 1)]);
      }
      for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
        vars__.emplace_back(tau_u_free__[(sym1__ - 1)]);
      }
      vars__.emplace_back(mu_alpha);
      vars__.emplace_back(mu_beta);
      for (int sym1__ = 1; sym1__ <= D; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= 2; ++sym2__) {
          vars__.emplace_back(
            rvalue(z_u, "z_u", index_uni(sym2__), index_uni(sym1__)));
        }
      }
      for (int sym1__ = 1; sym1__ <= ((2 * (2 - 1)) / 2); ++sym1__) {
        vars__.emplace_back(L_u_free__[(sym1__ - 1)]);
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // transform_inits_impl() 
    
  inline void get_param_names(std::vector<std::string>& names__) const {
    
    names__ = std::vector<std::string>{"gamma", "tau_u", "mu_alpha",
      "mu_beta", "z_u", "L_u", "u", "rho_u", "alpha", "beta", "sigma_alpha",
      "sigma_beta"};
    
    } // get_param_names() 
    
  inline void get_dims(std::vector<std::vector<size_t>>& dimss__) const {
    
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{
                                                                   static_cast<size_t>(D)
                                                                   },
      std::vector<size_t>{static_cast<size_t>(2)}, std::vector<size_t>{
      }, std::vector<size_t>{},
      std::vector<size_t>{static_cast<size_t>(2), static_cast<size_t>(D)},
      std::vector<size_t>{static_cast<size_t>(2), static_cast<size_t>(2)},
      std::vector<size_t>{static_cast<size_t>(D), static_cast<size_t>(2)},
      std::vector<size_t>{static_cast<size_t>(2), static_cast<size_t>(2)},
      std::vector<size_t>{static_cast<size_t>(D)},
      std::vector<size_t>{static_cast<size_t>(D)}, std::vector<size_t>{
      }, std::vector<size_t>{}};
    
    } // get_dims() 
    
  inline void constrained_param_names(
                                      std::vector<std::string>& param_names__,
                                      bool emit_transformed_parameters__ = true,
                                      bool emit_generated_quantities__ = true) const
    final {
    
    for (int sym1__ = 1; sym1__ <= D; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "gamma" + '.' + std::to_string(sym1__));
      } 
    }
    for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "tau_u" + '.' + std::to_string(sym1__));
      } 
    }
    param_names__.emplace_back(std::string() + "mu_alpha");
    param_names__.emplace_back(std::string() + "mu_beta");
    for (int sym1__ = 1; sym1__ <= D; ++sym1__) {
      {
        for (int sym2__ = 1; sym2__ <= 2; ++sym2__) {
          {
            param_names__.emplace_back(std::string() + "z_u" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
          } 
        }
      } 
    }
    for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
      {
        for (int sym2__ = 1; sym2__ <= 2; ++sym2__) {
          {
            param_names__.emplace_back(std::string() + "L_u" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
          } 
        }
      } 
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
        {
          for (int sym2__ = 1; sym2__ <= D; ++sym2__) {
            {
              param_names__.emplace_back(std::string() + "u" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
            } 
          }
        } 
      }
    }
    
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
        {
          for (int sym2__ = 1; sym2__ <= 2; ++sym2__) {
            {
              param_names__.emplace_back(std::string() + "rho_u" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
            } 
          }
        } 
      }
      for (int sym1__ = 1; sym1__ <= D; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "alpha" + '.' + std::to_string(sym1__));
        } 
      }
      for (int sym1__ = 1; sym1__ <= D; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "beta" + '.' + std::to_string(sym1__));
        } 
      }
      param_names__.emplace_back(std::string() + "sigma_alpha");
      param_names__.emplace_back(std::string() + "sigma_beta");
    }
    
    } // constrained_param_names() 
    
  inline void unconstrained_param_names(
                                        std::vector<std::string>& param_names__,
                                        bool emit_transformed_parameters__ = true,
                                        bool emit_generated_quantities__ = true) const
    final {
    
    for (int sym1__ = 1; sym1__ <= D; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "gamma" + '.' + std::to_string(sym1__));
      } 
    }
    for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "tau_u" + '.' + std::to_string(sym1__));
      } 
    }
    param_names__.emplace_back(std::string() + "mu_alpha");
    param_names__.emplace_back(std::string() + "mu_beta");
    for (int sym1__ = 1; sym1__ <= D; ++sym1__) {
      {
        for (int sym2__ = 1; sym2__ <= 2; ++sym2__) {
          {
            param_names__.emplace_back(std::string() + "z_u" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
          } 
        }
      } 
    }
    for (int sym1__ = 1; sym1__ <= ((2 * (2 - 1)) / 2); ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "L_u" + '.' + std::to_string(sym1__));
      } 
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
        {
          for (int sym2__ = 1; sym2__ <= D; ++sym2__) {
            {
              param_names__.emplace_back(std::string() + "u" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
            } 
          }
        } 
      }
    }
    
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= ((2 * (2 - 1)) / 2); ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "rho_u" + '.' + std::to_string(sym1__));
        } 
      }
      for (int sym1__ = 1; sym1__ <= D; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "alpha" + '.' + std::to_string(sym1__));
        } 
      }
      for (int sym1__ = 1; sym1__ <= D; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "beta" + '.' + std::to_string(sym1__));
        } 
      }
      param_names__.emplace_back(std::string() + "sigma_alpha");
      param_names__.emplace_back(std::string() + "sigma_beta");
    }
    
    } // unconstrained_param_names() 
    
  inline std::string get_constrained_sizedtypes() const {
    
    return std::string("[{\"name\":\"gamma\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(D) + "},\"block\":\"parameters\"},{\"name\":\"tau_u\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(2) + "},\"block\":\"parameters\"},{\"name\":\"mu_alpha\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"mu_beta\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"z_u\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(2) + ",\"cols\":" + std::to_string(D) + "},\"block\":\"parameters\"},{\"name\":\"L_u\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(2) + ",\"cols\":" + std::to_string(2) + "},\"block\":\"parameters\"},{\"name\":\"u\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(D) + ",\"cols\":" + std::to_string(2) + "},\"block\":\"transformed_parameters\"},{\"name\":\"rho_u\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(2) + ",\"cols\":" + std::to_string(2) + "},\"block\":\"generated_quantities\"},{\"name\":\"alpha\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(D) + "},\"block\":\"generated_quantities\"},{\"name\":\"beta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(D) + "},\"block\":\"generated_quantities\"},{\"name\":\"sigma_alpha\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"sigma_beta\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"}]");
    
    } // get_constrained_sizedtypes() 
    
  inline std::string get_unconstrained_sizedtypes() const {
    
    return std::string("[{\"name\":\"gamma\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(D) + "},\"block\":\"parameters\"},{\"name\":\"tau_u\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(2) + "},\"block\":\"parameters\"},{\"name\":\"mu_alpha\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"mu_beta\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"z_u\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(2) + ",\"cols\":" + std::to_string(D) + "},\"block\":\"parameters\"},{\"name\":\"L_u\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(((2 * (2 - 1)) / 2)) + "},\"block\":\"parameters\"},{\"name\":\"u\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(D) + ",\"cols\":" + std::to_string(2) + "},\"block\":\"transformed_parameters\"},{\"name\":\"rho_u\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(((2 * (2 - 1)) / 2)) + "},\"block\":\"generated_quantities\"},{\"name\":\"alpha\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(D) + "},\"block\":\"generated_quantities\"},{\"name\":\"beta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(D) + "},\"block\":\"generated_quantities\"},{\"name\":\"sigma_alpha\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"sigma_beta\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"}]");
    
    } // get_unconstrained_sizedtypes() 
    
  
    // Begin method overload boilerplate
    template <typename RNG>
    inline void write_array(RNG& base_rng,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                            const bool emit_transformed_parameters = true,
                            const bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      std::vector<double> vars_vec;
      vars_vec.reserve(vars.size());
      std::vector<int> params_i;
      write_array_impl(base_rng, params_r, params_i, vars_vec,
          emit_transformed_parameters, emit_generated_quantities, pstream);
      vars = Eigen::Map<Eigen::Matrix<double,Eigen::Dynamic,1>>(
        vars_vec.data(), vars_vec.size());
    }

    template <typename RNG>
    inline void write_array(RNG& base_rng, std::vector<double>& params_r,
                            std::vector<int>& params_i,
                            std::vector<double>& vars,
                            bool emit_transformed_parameters = true,
                            bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      write_array_impl(base_rng, params_r, params_i, vars,
       emit_transformed_parameters, emit_generated_quantities, pstream);
    }

    template <bool propto__, bool jacobian__, typename T_>
    inline T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
                       std::ostream* pstream = nullptr) const {
      Eigen::Matrix<int, -1, 1> params_i;
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }

    template <bool propto__, bool jacobian__, typename T__>
    inline T__ log_prob(std::vector<T__>& params_r,
                        std::vector<int>& params_i,
                        std::ostream* pstream = nullptr) const {
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }


    inline void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream = nullptr) const final {
      std::vector<double> params_r_vec;
      params_r_vec.reserve(params_r.size());
      std::vector<int> params_i;
      transform_inits_impl(context, params_i, params_r_vec, pstream);
      params_r = Eigen::Map<Eigen::Matrix<double,Eigen::Dynamic,1>>(
        params_r_vec.data(), params_r_vec.size());
    }
    inline void transform_inits(const stan::io::var_context& context,
                                std::vector<int>& params_i,
                                std::vector<double>& vars,
                                std::ostream* pstream = nullptr) const final {
      transform_inits_impl(context, params_i, vars, pstream);
    }

};
}
using stan_model = vasishth_model_namespace::vasishth_model;

#ifndef USING_R

// Boilerplate
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}

stan::math::profile_map& get_stan_profile_data() {
  return vasishth_model_namespace::profiles__;
}

#endif


